# Generated by Django 6.0.7 on 2026-08-06 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappnotificationmodel',
            name='user',
            field=models.ManyToManyField(related_name='whatsapp_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
