# Generated by Django 6.0.7 on 2026-08-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_whatsappnotificationmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappnotificationmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='whatsappnotificationmodel',
            name='users',
            field=models.ManyToManyField(blank=True, to='administration.whatsappnotificationmodel'),
        ),
    ]
