# Generated by Django 6.0.7 on 2026-08-07 00:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_remove_whatsappnotificationmodel_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappnotificationmodel',
            name='users',
            field=models.ManyToManyField(related_name='whatsapp_notification', to=settings.AUTH_USER_MODEL),
        ),
    ]
