# Generated by Django 6.0.7 on 2026-08-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_alter_whatsappnotificationmodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappnotificationmodel',
            name='company',
            field=models.CharField(blank=True, default='UnityPower-একতাই শক্তি', max_length=255, null=True),
        ),
    ]
