services:
  web:
    build: .
    # This runs migrations first, then starts the Django server
    command: >
      sh -c "python manage.py migrate && python manage.py makemigrations && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./db.sqlite3:/unity_power/db.sqlite3
    ports:
      - "8000:8000"
