# Generated by Django 6.0.7 on 2026-07-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_profile_avatar_alter_nominee_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[('Male', 'Male'), ('Female', 'Female')], default=1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.IntegerField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.IntegerField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu')], default=1),
        ),
    ]
