# Generated by Django 6.0.7 on 2026-07-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_profile_gender_alter_profile_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='marital_status',
            field=models.IntegerField(choices=[('Married', 'Married'), ('Unmarried', 'Unmarried')], default='Unmarried'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.IntegerField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu')], default='Muslim'),
        ),
    ]
