# Generated by Django 6.0.7 on 2026-07-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_alter_profile_gender_alter_profile_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='religion',
            field=models.CharField(choices=[('Muslim', 'Muslim'), ('Hindu', 'Hindu')], default='Muslim', max_length=50),
        ),
    ]
