# Generated by Django 6.0.7 on 2026-07-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0008_user_is_admin_user_is_finance_user_is_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Member', 'Member'), ('Chief-Adviser', 'Chief-Adviser'), ('President', 'President'), ('Vice-President', 'Vice-President'), ('Chief-Cashier', 'Chief-Cashier'), ('Assistant-Cashier', 'Assistant-Cashier'), ('Organizing-Committee', 'Organizing-Committee'), ('Editor', 'Editor'), ('Developer', 'Developer'), ('Hr', 'Hr'), ('Admin', 'Admin')], default='Member', max_length=100),
        ),
    ]
