# Generated by Django 6.0.7 on 2026-07-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
