# Generated by Django 6.0.7 on 2026-08-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0011_historicalcontactus_historicalnominee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofile',
            name='created_date',
            field=models.DateField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalprofile',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='updated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
