# Generated by Django 6.0.7 on 2026-08-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_alter_historicalprofile_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnominee',
            name='updated_date',
            field=models.DateTimeField(blank=True, default='2026-8-14', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nominee',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
