# Generated by Django 6.1.1 on 2026-09-16 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0013_alter_historicalnominee_updated_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnominee',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalnominee',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='history_user',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='user',
            field=models.ForeignKey(limit_choices_to=models.Q(('user_type', 'Developer'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='contact_us', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(('user_type', 'Developer'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='HistoricalContactUs',
        ),
        migrations.DeleteModel(
            name='HistoricalNominee',
        ),
        migrations.DeleteModel(
            name='HistoricalProfile',
        ),
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
