# Generated by Django 6.1.1 on 2026-09-16 18:53

import django.db.models.deletion
import finance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, default=5000, max_digits=15)),
                ('special_fee', models.DecimalField(decimal_places=2, default=20000, max_digits=15)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Properties Name', max_length=255)),
                ('details', models.TextField(default='Properties Descriptions')),
                ('document', models.ImageField(blank=True, null=True, upload_to='payment_doc')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to=models.Q(('user_type', 'Developer'), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(limit_choices_to=models.Q(('user_type', 'Developer'), _negated=True), related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=finance.models.generate_invoice_number, editable=False, max_length=20, unique=True)),
                ('amount_of_money', models.DecimalField(decimal_places=2, default='0.00', max_digits=11)),
                ('from_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pin_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('pay_year', models.IntegerField()),
                ('pay_month', models.IntegerField()),
                ('payment_note', models.CharField(blank=True, max_length=500, null=True)),
                ('is_accept', models.BooleanField(default=False)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('document', models.ImageField(blank=True, null=True, upload_to='payment_doc')),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to=models.Q(('user_type', 'Developer'), _negated=True), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('cashier', models.ForeignKey(default='Select Cashier', on_delete=django.db.models.deletion.CASCADE, to='finance.cashier')),
                ('payment_method', models.ForeignKey(default='Select Method', on_delete=django.db.models.deletion.CASCADE, to='finance.paymentmethod')),
                ('user', models.ForeignKey(limit_choices_to=models.Q(('user_type', 'Developer'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='payment_request', to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(default='Select Purpose', on_delete=django.db.models.deletion.CASCADE, to='finance.paymenttype')),
                ('properties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='finance.properties')),
                ('status', models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='finance.status')),
            ],
            options={
                'unique_together': {('user', 'pay_year', 'pay_month')},
            },
        ),
    ]
