# Generated by Django 6.0.7 on 2026-08-02 17:25

import django.db.models.deletion
import finance.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPropertiesBuySale',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='Properties Name', max_length=255)),
                ('description', models.TextField(default='Properties Descriptions')),
                ('document', models.TextField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical properties buy sale',
                'verbose_name_plural': 'historical properties buy sales',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PropertiesBuySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Properties Name', max_length=255)),
                ('description', models.TextField(default='Properties Descriptions')),
                ('document', models.ImageField(blank=True, null=True, upload_to='payment_doc')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties_approved', to=settings.AUTH_USER_MODEL)),
                ('user', models.ManyToManyField(related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default=finance.models.generate_invoice_number, editable=False, max_length=20, unique=True)),
                ('calculation_type', models.CharField(choices=[('Select Purpose', 'Select Purpose'), ('Savings', 'Savings'), ('Expense', 'Expense'), ('Loan', 'Loan'), ('Welfare', 'Welfare')], default='Select Purpose', max_length=100)),
                ('payment_method', models.CharField(choices=[('Select Method', 'Select Method'), ('Developments', 'Developments'), ('Bkash', 'Bkash'), ('Rocket', 'Rocket'), ('Cash', 'Cash'), ('Bank', 'Bank')], default='Select Method', max_length=100)),
                ('amount_of_money', models.DecimalField(decimal_places=2, default='0.00', max_digits=11)),
                ('from_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pin_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('pay_month', models.DateField(default=8)),
                ('cashier', models.CharField(choices=[('Select Cashier', 'Select Cashier'), ('Borhan-Uddin', 'Boran-Uddin'), ('Foysal-Ahammed', 'Foysal-Ahammed')], default='Select Cashier', max_length=100)),
                ('payment_note', models.CharField(blank=True, max_length=500, null=True)),
                ('is_accept', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('document', models.ImageField(blank=True, null=True, upload_to='payment_doc')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_request', to=settings.AUTH_USER_MODEL)),
                ('properties', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='finance.propertiesbuysale')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPaymentRequestModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('invoice_number', models.CharField(db_index=True, default=finance.models.generate_invoice_number, editable=False, max_length=20)),
                ('calculation_type', models.CharField(choices=[('Select Purpose', 'Select Purpose'), ('Savings', 'Savings'), ('Expense', 'Expense'), ('Loan', 'Loan'), ('Welfare', 'Welfare')], default='Select Purpose', max_length=100)),
                ('payment_method', models.CharField(choices=[('Select Method', 'Select Method'), ('Developments', 'Developments'), ('Bkash', 'Bkash'), ('Rocket', 'Rocket'), ('Cash', 'Cash'), ('Bank', 'Bank')], default='Select Method', max_length=100)),
                ('amount_of_money', models.DecimalField(decimal_places=2, default='0.00', max_digits=11)),
                ('from_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pin_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('pay_month', models.DateField(default=8)),
                ('cashier', models.CharField(choices=[('Select Cashier', 'Select Cashier'), ('Borhan-Uddin', 'Boran-Uddin'), ('Foysal-Ahammed', 'Foysal-Ahammed')], default='Select Cashier', max_length=100)),
                ('payment_note', models.CharField(blank=True, max_length=500, null=True)),
                ('is_accept', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('approved_at', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('document', models.TextField(blank=True, max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('properties', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='finance.propertiesbuysale')),
            ],
            options={
                'verbose_name': 'historical payment request model',
                'verbose_name_plural': 'historical payment request models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
