# Generated by Django 6.1.1 on 2026-09-16 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='status',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='finance.status'),
        ),
    ]
