# Generated by Django 6.0.7 on 2026-08-02 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentrequestmodel',
            name='pay_month',
            field=models.DateField(default=datetime.date(2026, 8, 2)),
        ),
        migrations.AlterField(
            model_name='paymentrequestmodel',
            name='pay_month',
            field=models.DateField(default=datetime.date(2026, 8, 2)),
        ),
    ]
