# Generated by Django 6.0.7 on 2026-08-06 23:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_historicalpaymentrequestmodel_pay_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentrequestmodel',
            name='pay_month',
            field=models.DateField(default=datetime.date(2026, 8, 7)),
        ),
        migrations.AlterField(
            model_name='paymentrequestmodel',
            name='pay_month',
            field=models.DateField(default=datetime.date(2026, 8, 7)),
        ),
    ]
