# Generated by Django 6.1.1 on 2026-09-17 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_paymentmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='invoice_id', editable=False, max_length=20, unique=True)),
                ('due_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=11)),
                ('pay_year', models.IntegerField()),
                ('pay_month', models.IntegerField()),
                ('penalty_fee', models.DecimalField(decimal_places=2, default='0.00', max_digits=11)),
                ('is_penalty', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='finance.status')),
                ('user', models.ForeignKey(limit_choices_to=models.Q(('user_type', 'Developer'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='due_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
