# Generated by Django 6.1.1 on 2026-09-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_duepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duepayment',
            name='invoice_number',
        ),
    ]
