# Generated by Django 6.0.7 on 2026-08-09 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_historicalpaymentrequestmodel_pay_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, default=5000, max_digits=15)),
                ('special_fee', models.DecimalField(decimal_places=2, default=20000, max_digits=15)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='historicalpaymentrequestmodel',
            name='pay_month',
            field=models.DateField(default=datetime.date(2026, 8, 9)),
        ),
        migrations.AlterField(
            model_name='paymentrequestmodel',
            name='pay_month',
            field=models.DateField(default=datetime.date(2026, 8, 9)),
        ),
    ]
