# Generated by Django 6.0.7 on 2026-08-11 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_feeschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaymentrequestmodel',
            name='pay_year',
            field=models.DateField(default=datetime.date(2026, 8, 11)),
        ),
        migrations.AddField(
            model_name='paymentrequestmodel',
            name='pay_year',
            field=models.DateField(default=datetime.date(2026, 8, 11)),
        ),
        migrations.AlterField(
            model_name='historicalpaymentrequestmodel',
            name='pay_month',
            field=models.DateField(default=datetime.date(2026, 8, 11)),
        ),
        migrations.AlterField(
            model_name='paymentrequestmodel',
            name='pay_month',
            field=models.DateField(default=datetime.date(2026, 8, 11)),
        ),
    ]
