# Generated by Django 6.1.1 on 2026-09-17 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_duepayment_penalty_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSummery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_due_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('total_penalty_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=20)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(limit_choices_to=models.Q(('user_type', 'Developer'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='payment_summery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
