# Generated by Django 6.0.7 on 2026-08-11 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_historicalpaymentrequestmodel_pay_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaymentrequestmodel',
            name='pay_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalpaymentrequestmodel',
            name='pay_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentrequestmodel',
            name='pay_month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentrequestmodel',
            name='pay_year',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='paymentrequestmodel',
            unique_together={('user', 'pay_year', 'pay_month')},
        ),
    ]
