# Generated by Django 6.1.1 on 2026-09-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_paymentsummery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duepayment',
            name='penalty_fee',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=11),
        ),
    ]
