# Generated by Django 6.0.7 on 2026-08-14 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_historicalpaymentrequestmodel_pay_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalpropertiesbuysale',
            old_name='description',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='propertiesbuysale',
            old_name='description',
            new_name='details',
        ),
    ]
