# Generated by Django 6.1.1 on 2026-09-18 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_duepayment_status_alter_paymentmodel_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmodel',
            unique_together={('invoice_number',)},
        ),
    ]
