# Generated by Django 6.1.1 on 2026-09-18 14:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_paymentmodel_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentsummery',
            unique_together={('user',)},
        ),
    ]
