# Generated by Django 6.1.1 on 2026-09-18 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_paymentsummery_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentsummery',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='paymentsummery',
            name='user',
            field=models.OneToOneField(limit_choices_to=models.Q(('user_type', 'Developer'), _negated=True), on_delete=django.db.models.deletion.CASCADE, related_name='payment_summery', to=settings.AUTH_USER_MODEL),
        ),
    ]
