# Generated by Django 6.1.1 on 2026-09-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_paymentsummery_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duepayment',
            name='total_due_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=11),
        ),
    ]
