# Generated by Django 6.1.1 on 2026-09-19 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_duepayment_total_due_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsummery',
            name='total_due_and_penalty_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=20),
        ),
    ]
