# Generated by Django 6.1.1 on 2026-09-19 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_paymentsummery_total_due_and_penalty_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsummery',
            name='total_due_and_penalty_amount',
        ),
    ]
